// Curated few-shot examples. The assistant output matches the JSON schema
// defined in prompt.ts. Keep the list diverse and short.

export const FEW_SHOT_EXAMPLES: Array<{ input: string; output: unknown }> = [
  {
    input: 'rice 400',
    output: {
      type: 'expense',
      amount: 400,
      category: 'Food',
      group: null,
      note: 'rice',
      occurred_at_hint: null,
      lending: null,
      confidence: 0.9,
      reasoning: 'rice → Food',
    },
  },
  {
    input: 'SIP 10000',
    output: {
      type: 'investment',
      amount: 10000,
      category: 'SIP',
      group: null,
      note: 'SIP',
      occurred_at_hint: null,
      lending: null,
      confidence: 0.95,
      reasoning: 'SIP keyword',
    },
  },
  {
    input: 'lent Ravi 2000',
    output: {
      type: 'lending',
      amount: 2000,
      category: 'Lent',
      group: null,
      note: 'lent Ravi',
      occurred_at_hint: null,
      lending: { counterparty: 'Ravi', direction: 'lent' },
      confidence: 0.95,
      reasoning: 'lent verb with counterparty Ravi',
    },
  },
  {
    input: 'uber 230 office',
    output: {
      type: 'expense',
      amount: 230,
      category: 'Transport',
      group: 'Office',
      note: 'uber',
      occurred_at_hint: null,
      lending: null,
      confidence: 0.9,
      reasoning: 'uber → Transport; group Office',
    },
  },
  {
    input: 'salary credited 95k',
    output: {
      type: 'income',
      amount: 95000,
      category: 'Salary',
      group: null,
      note: 'salary credited',
      occurred_at_hint: null,
      lending: null,
      confidence: 0.95,
      reasoning: 'salary → Income/Salary; 95k → 95000',
    },
  },
  {
    input: 'borrowed 500 from Aarav yesterday',
    output: {
      type: 'lending',
      amount: 500,
      category: 'Borrowed',
      group: null,
      note: 'borrowed from Aarav',
      occurred_at_hint: 'yesterday',
      lending: { counterparty: 'Aarav', direction: 'borrowed' },
      confidence: 0.9,
      reasoning: 'borrowed from Aarav',
    },
  },
  {
    input: 'moved 5k to savings',
    output: {
      type: 'transfer',
      amount: 5000,
      category: 'Transfer',
      group: null,
      note: 'moved to savings',
      occurred_at_hint: null,
      lending: null,
      confidence: 0.85,
      reasoning: 'money movement between own accounts',
    },
  },
  {
    input: 'petrol 1500',
    output: {
      type: 'expense',
      amount: 1500,
      category: 'Fuel',
      group: null,
      note: 'petrol',
      occurred_at_hint: null,
      lending: null,
      confidence: 0.95,
      reasoning: 'petrol → Fuel',
    },
  },
];
